[project]
name = "Graphene-BE"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Graphene-Fed", email = "amase.cocoa@gmail.com"},
]
dependencies = [
    "fastapi>=0.111.0",
    "aiohttp>=3.9.5",
    "orjson>=3.10.3",
    "cryptography>=42.0.7",
    "granian>=1.4.1",
    "uvicorn[standard]>=0.30.0",
    "pyfiglet>=1.0.2",
    "cleo>=2.1.0",
]
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "AGPL-3.0-or-later"}


[tool.pdm]
distribution = false

[tool.pdm.scripts]
serve = "granian --interface asgi main:app"
"uvicorn:serve" = "uvicorn main:app"
dev = "uvicorn main:app --reload"
generate_schema = "python ./genschema.py"
# grapctl

[project.scripts]

[project.urls]
"Homepage" = "https://github.com/graphene-fed/Graphene-BE"
"Bug Tracker" = "https://github.com/graphene-fed/Graphene-BE/issues"