url: https://example.com
port: 8000

database:
  host: "db"
  port: 5432
  user: "hol0"
  name: "hol0db"
  password: "hol0pass"

job:
  host: "redis"
  port: 6379

debug:
  enable: true
  profiling: false
  nossl: false