name: Run python unit tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-311:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install -r requirements.txt

    - name: Generate Prisma Models from Schema
      run: |
        python app/utils/combine.py
        prisma generate

    - name: Run tests with coverage
      run: |
        pytest --cov=./ --cov-report=xml

    - name: Save coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.xml
  test-312:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install -r requirements.txt

    - name: Generate Prisma Models from Schema
      run: |
        python app/utils/combine.py
        prisma generate

    - name: Run tests with coverage
      run: |
        pytest --cov=./ --cov-report=xml

    - name: Save coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.xml